# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: style
        name: Format code style
        entry: poetry run nox -t style -- --
        language: system
        types: [python]
        files: \.py$

    -   id: tests
        name: Run tests
        entry: poetry run nox -t coverage
        pass_filenames: false
        language: system
        types: [python]
        files: \.py$
