# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
        exclude: ^(poetry\.lock|requirements\.txt)$
        args: [ "--fix=lf" ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ push ]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
      - id: poetry-install
